[package]
name = "schist-tools-paint"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-i18n.workspace = true
schist-compositor.workspace = true
schist-core.workspace = true
schist-plugin-api.workspace = true
schist-pixel-ops.workspace = true
schist-color.workspace = true
rustc-hash.workspace = true
