[package]
name = "schist-compositor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-colormgmt.workspace = true
schist-core.workspace = true
schist-adjustments.workspace = true
serde_json.workspace = true
log.workspace = true
schist-pixel-ops.workspace = true
schist-color.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
schist-layer-fx.workspace = true
