//! Backer data and logos are embedded at build time, including on the web.

#[cfg(test)]
mod api;
mod data;

use std::sync::{Arc, OnceLock};

pub use data::Backers;

include!(concat!(env!("OUT_DIR"), "/backer_logos.rs"));

pub fn catalog() -> &'static Backers {
    static CATALOG: OnceLock<Backers> = OnceLock::new();
    CATALOG.get_or_init(|| {
        serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/backers.json")))
            .expect("backers.json was generated by the build script")
    })
}

pub fn logo(url: &str) -> Option<Arc<gpui::Image>> {
    static IMAGES: OnceLock<Vec<(&'static str, Arc<gpui::Image>)>> = OnceLock::new();
    IMAGES
        .get_or_init(|| {
            LOGOS
                .iter()
                .map(|(url, bytes)| {
                    let format = image::guess_format(bytes)
                        .ok()
                        .and_then(|format| gpui::ImageFormat::from_mime_type(format.to_mime_type()))
                        .unwrap_or(gpui::ImageFormat::Svg);
                    (
                        *url,
                        Arc::new(gpui::Image::from_bytes(format, bytes.to_vec())),
                    )
                })
                .collect()
        })
        .iter()
        .find(|(source, _)| *source == url)
        .map(|(_, image)| image.clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shipped_catalog_has_embedded_logos() {
        let catalog = catalog();
        assert!(url::Url::parse(&catalog.support_url).is_ok());
        for tier in &catalog.tiers {
            assert!(!tier.name.trim().is_empty());
            for backer in &tier.backers {
                assert!(!backer.name.trim().is_empty());
                if let Some(url) = &backer.url {
                    assert!(url::Url::parse(url).is_ok());
                }
                if let Some(entry) = &backer.logo {
                    assert!(entry.width > 0);
                    for url in std::iter::once(&entry.light).chain(entry.dark.iter()) {
                        assert!(logo(url).is_some(), "missing embedded logo: {url}");
                    }
                }
            }
        }
        for (url, bytes) in LOGOS {
            if image::guess_format(bytes).is_ok() {
                image::load_from_memory(bytes).unwrap_or_else(|e| panic!("{url}: {e}"));
            } else {
                assert!(
                    std::str::from_utf8(bytes).unwrap().contains("<svg"),
                    "{url}"
                );
            }
        }
    }

    #[test]
    fn catalog_accepts_text_only_backers_and_light_only_logos() {
        let catalog: Backers = serde_json::from_str(
            r#"{
            "support_url": "https://backers.schist.app",
            "tiers": [{"name": "Community", "backers": [
                {"name": "Someone"},
                {"name": "A brand", "logo": {"light": "https://example.com/logo.png"}}
            ]}]
        }"#,
        )
        .unwrap();
        let backers = &catalog.tiers[0].backers;
        assert!(backers[0].url.is_none());
        assert!(backers[0].logo.is_none());
        let logo = backers[1].logo.as_ref().unwrap();
        assert!(logo.dark.is_none());
        assert_eq!(logo.width, 120);
    }
}
