[package]
name = "schist-tools-warp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-i18n.workspace = true
rayon.workspace = true
schist-core.workspace = true
schist-color.workspace = true
schist-fx.workspace = true
schist-plugin-api.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(schist_library)"] }
