[package]
name = "schist-tools-type"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-core.workspace = true
schist-plugin-api.workspace = true
schist-color.workspace = true
schist-text-engine.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[dev-dependencies]
schist-codec-psd.workspace = true
