//! Disposable break glyphs reuse discretionary shaping, then map every public
//! position back to the original text. No generated byte becomes an edit anchor.
use super::{Layout, TextSpec};
use unicode_segmentation::UnicodeSegmentation;

struct Insertion {
    source: usize,
    visual: usize,
}

pub(super) struct Projection {
    pub spec: TextSpec,
    insertions: Vec<Insertion>,
    source: String,
}

impl Projection {
    pub fn new(spec: &TextSpec, wrapping: bool) -> Option<Self> {
        if spec.hyphenation_breaks.is_empty() && !spec.show_final_generated_hyphen {
            return None;
        }
        if !wrapping && !spec.show_final_generated_hyphen {
            return None;
        }
        let text = &spec.text;
        let boundaries = text
            .grapheme_indices(true)
            .map(|(at, _)| at)
            .collect::<Vec<_>>();
        let mut points = spec
            .hyphenation_breaks
            .iter()
            .copied()
            .filter(|at| {
                *at > 0
                    && *at < text.len()
                    && boundaries.binary_search(at).is_ok()
                    && spec.allows_wrap_at(*at)
                    && text[..*at]
                        .chars()
                        .next_back()
                        .is_some_and(|c| !c.is_whitespace() && c != '\u{ad}')
                    && text[*at..]
                        .chars()
                        .next()
                        .is_some_and(|c| !c.is_whitespace() && c != '\u{ad}')
            })
            .collect::<Vec<_>>();
        if spec.show_final_generated_hyphen
            && text
                .chars()
                .next_back()
                .is_some_and(|c| !c.is_whitespace() && c != '\u{ad}')
        {
            points.push(text.len());
        }
        points.sort_unstable();
        points.dedup();
        if points.is_empty() {
            return None;
        }
        let insertions = points
            .iter()
            .enumerate()
            .map(|(i, at)| Insertion {
                source: *at,
                visual: *at + i * '\u{ad}'.len_utf8(),
            })
            .collect::<Vec<_>>();
        let mut projected = spec.clone();
        projected.hyphenation_breaks.clear();
        projected.show_final_generated_hyphen = false;
        projected.show_final_soft_hyphen |= points.last() == Some(&text.len());
        projected.text.clear();
        let mut from = 0;
        for at in &points {
            projected.text.push_str(&text[from..*at]);
            projected.text.push('\u{ad}');
            from = *at;
        }
        projected.text.push_str(&text[from..]);
        let after = |at: usize| at + points.partition_point(|p| *p <= at) * '\u{ad}'.len_utf8();
        for run in &mut projected.runs {
            // An insertion belongs to the preceding source style. Runs ending
            // here include it; a run beginning here starts after it.
            run.start = after(run.start.min(text.len()));
            run.end = after(run.end.min(text.len()));
        }
        Some(Self {
            spec: projected,
            insertions,
            source: text.clone(),
        })
    }

    fn insertion(&self, byte: usize) -> Option<&Insertion> {
        let index = self.insertions.partition_point(|i| i.visual <= byte);
        index
            .checked_sub(1)
            .and_then(|i| self.insertions.get(i))
            .filter(|i| byte < i.visual + '\u{ad}'.len_utf8())
    }

    fn source_at(&self, byte: usize) -> usize {
        if let Some(insertion) = self.insertion(byte) {
            return insertion.source;
        }
        byte - self
            .insertions
            .partition_point(|i| i.visual + '\u{ad}'.len_utf8() <= byte)
            * '\u{ad}'.len_utf8()
    }

    pub fn restore(&self, mut layout: Layout) -> Layout {
        let selected = layout
            .lines
            .iter()
            .filter_map(|line| {
                line.discretionary_hyphen
                    .then(|| self.insertion(line.end.saturating_sub(1)))
                    .flatten()
            })
            .map(|i| i.visual)
            .collect::<std::collections::HashSet<_>>();
        let ends = layout
            .chars
            .iter()
            .filter_map(|c| {
                self.insertion(c.byte)
                    .filter(|i| selected.contains(&i.visual))
                    .map(|i| (i.source, c.end_x))
            })
            .collect::<Vec<_>>();
        for glyph in &mut layout.glyphs {
            glyph.byte = if let Some(insertion) = self.insertion(glyph.byte) {
                // Paint/font ownership belongs to the preceding source scalar;
                // the generated glyph itself has no source character.
                self.source[..insertion.source]
                    .char_indices()
                    .next_back()
                    .map_or(0, |(at, _)| at)
            } else {
                self.source_at(glyph.byte)
            };
        }
        layout.chars.retain_mut(|c| {
            if self.insertion(c.byte).is_some() {
                return false;
            }
            c.byte = self.source_at(c.byte);
            true
        });
        if !ends.is_empty() {
            // Shaping can place RTL characters in visual order. Index source
            // positions once instead of rescanning the story for every line.
            let mut positions = layout
                .chars
                .iter()
                .enumerate()
                .map(|(i, c)| (c.byte, i))
                .collect::<Vec<_>>();
            positions.sort_by_key(|(byte, _)| *byte);
            for (at, end_x) in ends {
                let index = positions.partition_point(|(byte, _)| *byte < at);
                if let Some((_, index)) = index.checked_sub(1).and_then(|i| positions.get(i)) {
                    layout.chars[*index].end_x = end_x;
                }
            }
        }
        for line in &mut layout.lines {
            if line.discretionary_hyphen && self.insertion(line.end.saturating_sub(1)).is_some() {
                line.discretionary_hyphen = false;
                line.generated_hyphen = true;
            }
            line.start = self.source_at(line.start);
            line.end = self.source_at(line.end);
        }
        for (at, _) in &mut layout.tab_stops {
            *at = self.source_at(*at);
        }
        layout
    }
}
