[package]
name = "schist-video"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
schist-i18n.workspace = true
anyhow.workspace = true
log.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = [
    "std",
    "NSString",
] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22"
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = [
    "std",
    "NSString",
] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libloading.workspace = true

[dev-dependencies]
schist-gallery.workspace = true
tempfile = "3"
