// Generated by tools/generate-i18n-plurals.py; do not edit.
// Unicode CLDR 48. See ../data/LICENSE-Unicode.txt.
// Cardinal counts are u64: n = i, and v/w/f/t/c/e = 0.

pub(crate) fn category(language: &str, n: u64) -> &'static str {
    match language {
        "bm" | "bo" | "dz" | "hnj" | "id" | "ig" | "ii" | "in" | "ja" | "jbo" | "jv" | "jw"
        | "kde" | "kea" | "km" | "ko" | "lkt" | "lo" | "ms" | "my" | "nqo" | "osa" | "root"
        | "sah" | "ses" | "sg" | "su" | "th" | "to" | "tpi" | "vi" | "wo" | "yo" | "yue" | "zh" => {
            "other"
        }
        "am" | "as" | "bn" | "doi" | "fa" | "gu" | "hi" | "kn" | "kok" | "kok_Latn" | "pcm"
        | "zu" => {
            if n == 0 || n == 1 {
                return "one";
            }
            "other"
        }
        "ff" | "hy" | "kab" => {
            if n == 0 || n == 1 {
                return "one";
            }
            "other"
        }
        "ast" | "de" | "en" | "et" | "fi" | "fy" | "gl" | "ia" | "ie" | "io" | "ji" | "lij"
        | "nl" | "sc" | "sv" | "sw" | "ur" | "yi" => {
            if n == 1 {
                return "one";
            }
            "other"
        }
        "si" => {
            if n == 0 || n == 1 {
                return "one";
            }
            "other"
        }
        "ak" | "bho" | "csw" | "guw" | "ln" | "mg" | "nso" | "pa" | "ti" | "wa" => {
            if (0..=1).contains(&(n)) {
                return "one";
            }
            "other"
        }
        "tzm" => {
            if (0..=1).contains(&(n)) || (11..=99).contains(&(n)) {
                return "one";
            }
            "other"
        }
        "af" | "an" | "asa" | "az" | "bal" | "bem" | "bez" | "bg" | "brx" | "ce" | "cgg"
        | "chr" | "ckb" | "dv" | "ee" | "el" | "eo" | "eu" | "fo" | "fur" | "gsw" | "ha"
        | "haw" | "hu" | "jgo" | "jmc" | "ka" | "kaj" | "kcg" | "kk" | "kkj" | "kl" | "ks"
        | "ksb" | "ku" | "ky" | "lb" | "lg" | "mas" | "mgo" | "ml" | "mn" | "mr" | "nah" | "nb"
        | "nd" | "ne" | "nn" | "nnh" | "no" | "nr" | "ny" | "nyn" | "om" | "or" | "os" | "pap"
        | "ps" | "rm" | "rof" | "rwk" | "saq" | "sd" | "sdh" | "seh" | "sn" | "so" | "sq"
        | "ss" | "ssy" | "st" | "syr" | "ta" | "te" | "teo" | "tig" | "tk" | "tn" | "tr" | "ts"
        | "ug" | "uz" | "ve" | "vo" | "vun" | "wae" | "xh" | "xog" => {
            if n == 1 {
                return "one";
            }
            "other"
        }
        "da" => {
            if n == 1 {
                return "one";
            }
            "other"
        }
        "is" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            "other"
        }
        "mk" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            "other"
        }
        "ceb" | "fil" | "tl" => {
            if (n == 1 || n == 2 || n == 3) || !(n % 10 == 4 || n % 10 == 6 || n % 10 == 9) {
                return "one";
            }
            "other"
        }
        "lv" | "prg" => {
            if n.is_multiple_of(10) || (11..=19).contains(&(n % 100)) {
                return "zero";
            }
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            "other"
        }
        "lag" => {
            if n == 0 {
                return "zero";
            }
            if (n == 0 || n == 1) && !(n == 0) {
                return "one";
            }
            "other"
        }
        "blo" | "cv" | "ksh" => {
            if n == 0 {
                return "zero";
            }
            if n == 1 {
                return "one";
            }
            "other"
        }
        "he" | "iw" => {
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            "other"
        }
        "iu" | "naq" | "sat" | "se" | "sma" | "smi" | "smj" | "smn" | "sms" => {
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            "other"
        }
        "shi" => {
            if n == 0 || n == 1 {
                return "one";
            }
            if (2..=10).contains(&(n)) {
                return "few";
            }
            "other"
        }
        "mo" | "ro" => {
            if n == 1 {
                return "one";
            }
            if n == 0 || !(n == 1) && (1..=19).contains(&(n % 100)) {
                return "few";
            }
            "other"
        }
        "bs" | "hr" | "sh" | "sr" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            if (2..=4).contains(&(n % 10)) && !((12..=14).contains(&(n % 100))) {
                return "few";
            }
            "other"
        }
        "fr" => {
            if n == 0 || n == 1 {
                return "one";
            }
            if !(n == 0) && n.is_multiple_of(1000000) {
                return "many";
            }
            "other"
        }
        "pt" => {
            if (0..=1).contains(&(n)) {
                return "one";
            }
            if !(n == 0) && n.is_multiple_of(1000000) {
                return "many";
            }
            "other"
        }
        "ca" | "it" | "lld" | "pt_PT" | "scn" | "vec" => {
            if n == 1 {
                return "one";
            }
            if !(n == 0) && n.is_multiple_of(1000000) {
                return "many";
            }
            "other"
        }
        "es" => {
            if n == 1 {
                return "one";
            }
            if !(n == 0) && n.is_multiple_of(1000000) {
                return "many";
            }
            "other"
        }
        "gd" => {
            if n == 1 || n == 11 {
                return "one";
            }
            if n == 2 || n == 12 {
                return "two";
            }
            if (3..=10).contains(&(n)) || (13..=19).contains(&(n)) {
                return "few";
            }
            "other"
        }
        "sl" => {
            if n % 100 == 1 {
                return "one";
            }
            if n % 100 == 2 {
                return "two";
            }
            if (3..=4).contains(&(n % 100)) {
                return "few";
            }
            "other"
        }
        "dsb" | "hsb" => {
            if n % 100 == 1 {
                return "one";
            }
            if n % 100 == 2 {
                return "two";
            }
            if (3..=4).contains(&(n % 100)) {
                return "few";
            }
            "other"
        }
        "cs" | "sk" => {
            if n == 1 {
                return "one";
            }
            if (2..=4).contains(&(n)) {
                return "few";
            }
            "other"
        }
        "pl" => {
            if n == 1 {
                return "one";
            }
            if (2..=4).contains(&(n % 10)) && !((12..=14).contains(&(n % 100))) {
                return "few";
            }
            if !(n == 1) && (0..=1).contains(&(n % 10))
                || (5..=9).contains(&(n % 10))
                || (12..=14).contains(&(n % 100))
            {
                return "many";
            }
            "other"
        }
        "be" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            if (2..=4).contains(&(n % 10)) && !((12..=14).contains(&(n % 100))) {
                return "few";
            }
            if n.is_multiple_of(10) || (5..=9).contains(&(n % 10)) || (11..=14).contains(&(n % 100))
            {
                return "many";
            }
            "other"
        }
        "lt" => {
            if n % 10 == 1 && !((11..=19).contains(&(n % 100))) {
                return "one";
            }
            if (2..=9).contains(&(n % 10)) && !((11..=19).contains(&(n % 100))) {
                return "few";
            }
            "other"
        }
        "ru" | "uk" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            if (2..=4).contains(&(n % 10)) && !((12..=14).contains(&(n % 100))) {
                return "few";
            }
            if n.is_multiple_of(10) || (5..=9).contains(&(n % 10)) || (11..=14).contains(&(n % 100))
            {
                return "many";
            }
            "other"
        }
        "sgs" => {
            if n % 10 == 1 && !(n % 100 == 11) {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            if !(n == 2) && (2..=9).contains(&(n % 10)) && !((11..=19).contains(&(n % 100))) {
                return "few";
            }
            "other"
        }
        "br" => {
            if n % 10 == 1 && !(n % 100 == 11 || n % 100 == 71 || n % 100 == 91) {
                return "one";
            }
            if n % 10 == 2 && !(n % 100 == 12 || n % 100 == 72 || n % 100 == 92) {
                return "two";
            }
            if ((3..=4).contains(&(n % 10)) || n % 10 == 9)
                && !((10..=19).contains(&(n % 100))
                    || (70..=79).contains(&(n % 100))
                    || (90..=99).contains(&(n % 100)))
            {
                return "few";
            }
            if !(n == 0) && n.is_multiple_of(1000000) {
                return "many";
            }
            "other"
        }
        "mt" => {
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            if n == 0 || (3..=10).contains(&(n % 100)) {
                return "few";
            }
            if (11..=19).contains(&(n % 100)) {
                return "many";
            }
            "other"
        }
        "ga" => {
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            if (3..=6).contains(&(n)) {
                return "few";
            }
            if (7..=10).contains(&(n)) {
                return "many";
            }
            "other"
        }
        "gv" => {
            if n % 10 == 1 {
                return "one";
            }
            if n % 10 == 2 {
                return "two";
            }
            if n.is_multiple_of(100)
                || n % 100 == 20
                || n % 100 == 40
                || n % 100 == 60
                || n % 100 == 80
            {
                return "few";
            }
            "other"
        }
        "kw" => {
            if n == 0 {
                return "zero";
            }
            if n == 1 {
                return "one";
            }
            if (n % 100 == 2 || n % 100 == 22 || n % 100 == 42 || n % 100 == 62 || n % 100 == 82)
                || n.is_multiple_of(1000)
                    && ((1000..=20000).contains(&(n % 100000))
                        || n % 100000 == 40000
                        || n % 100000 == 60000
                        || n % 100000 == 80000)
                || !(n == 0) && n % 1000000 == 100000
            {
                return "two";
            }
            if n % 100 == 3 || n % 100 == 23 || n % 100 == 43 || n % 100 == 63 || n % 100 == 83 {
                return "few";
            }
            if !(n == 1)
                && (n % 100 == 1
                    || n % 100 == 21
                    || n % 100 == 41
                    || n % 100 == 61
                    || n % 100 == 81)
            {
                return "many";
            }
            "other"
        }
        "ar" | "ars" => {
            if n == 0 {
                return "zero";
            }
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            if (3..=10).contains(&(n % 100)) {
                return "few";
            }
            if (11..=99).contains(&(n % 100)) {
                return "many";
            }
            "other"
        }
        "cy" => {
            if n == 0 {
                return "zero";
            }
            if n == 1 {
                return "one";
            }
            if n == 2 {
                return "two";
            }
            if n == 3 {
                return "few";
            }
            if n == 6 {
                return "many";
            }
            "other"
        }
        _ => "other",
    }
}

pub(crate) fn categories(language: &str) -> &'static [&'static str] {
    match language {
        "bm" | "bo" | "dz" | "hnj" | "id" | "ig" | "ii" | "in" | "ja" | "jbo" | "jv" | "jw"
        | "kde" | "kea" | "km" | "ko" | "lkt" | "lo" | "ms" | "my" | "nqo" | "osa" | "root"
        | "sah" | "ses" | "sg" | "su" | "th" | "to" | "tpi" | "vi" | "wo" | "yo" | "yue" | "zh" => {
            &["other"]
        }
        "am" | "as" | "bn" | "doi" | "fa" | "gu" | "hi" | "kn" | "kok" | "kok_Latn" | "pcm"
        | "zu" => &["one", "other"],
        "ff" | "hy" | "kab" => &["one", "other"],
        "ast" | "de" | "en" | "et" | "fi" | "fy" | "gl" | "ia" | "ie" | "io" | "ji" | "lij"
        | "nl" | "sc" | "sv" | "sw" | "ur" | "yi" => &["one", "other"],
        "si" => &["one", "other"],
        "ak" | "bho" | "csw" | "guw" | "ln" | "mg" | "nso" | "pa" | "ti" | "wa" => {
            &["one", "other"]
        }
        "tzm" => &["one", "other"],
        "af" | "an" | "asa" | "az" | "bal" | "bem" | "bez" | "bg" | "brx" | "ce" | "cgg"
        | "chr" | "ckb" | "dv" | "ee" | "el" | "eo" | "eu" | "fo" | "fur" | "gsw" | "ha"
        | "haw" | "hu" | "jgo" | "jmc" | "ka" | "kaj" | "kcg" | "kk" | "kkj" | "kl" | "ks"
        | "ksb" | "ku" | "ky" | "lb" | "lg" | "mas" | "mgo" | "ml" | "mn" | "mr" | "nah" | "nb"
        | "nd" | "ne" | "nn" | "nnh" | "no" | "nr" | "ny" | "nyn" | "om" | "or" | "os" | "pap"
        | "ps" | "rm" | "rof" | "rwk" | "saq" | "sd" | "sdh" | "seh" | "sn" | "so" | "sq"
        | "ss" | "ssy" | "st" | "syr" | "ta" | "te" | "teo" | "tig" | "tk" | "tn" | "tr" | "ts"
        | "ug" | "uz" | "ve" | "vo" | "vun" | "wae" | "xh" | "xog" => &["one", "other"],
        "da" => &["one", "other"],
        "is" => &["one", "other"],
        "mk" => &["one", "other"],
        "ceb" | "fil" | "tl" => &["one", "other"],
        "lv" | "prg" => &["zero", "one", "other"],
        "lag" => &["zero", "one", "other"],
        "blo" | "cv" | "ksh" => &["zero", "one", "other"],
        "he" | "iw" => &["one", "two", "other"],
        "iu" | "naq" | "sat" | "se" | "sma" | "smi" | "smj" | "smn" | "sms" => {
            &["one", "two", "other"]
        }
        "shi" => &["one", "few", "other"],
        "mo" | "ro" => &["one", "few", "other"],
        "bs" | "hr" | "sh" | "sr" => &["one", "few", "other"],
        "fr" => &["one", "many", "other"],
        "pt" => &["one", "many", "other"],
        "ca" | "it" | "lld" | "pt_PT" | "scn" | "vec" => &["one", "many", "other"],
        "es" => &["one", "many", "other"],
        "gd" => &["one", "two", "few", "other"],
        "sl" => &["one", "two", "few", "other"],
        "dsb" | "hsb" => &["one", "two", "few", "other"],
        "cs" | "sk" => &["one", "few", "other"],
        "pl" => &["one", "few", "many", "other"],
        "be" => &["one", "few", "many", "other"],
        "lt" => &["one", "few", "other"],
        "ru" | "uk" => &["one", "few", "many", "other"],
        "sgs" => &["one", "two", "few", "other"],
        "br" => &["one", "two", "few", "many", "other"],
        "mt" => &["one", "two", "few", "many", "other"],
        "ga" => &["one", "two", "few", "many", "other"],
        "gv" => &["one", "two", "few", "other"],
        "kw" => &["zero", "one", "two", "few", "many", "other"],
        "ar" | "ars" => &["zero", "one", "two", "few", "many", "other"],
        "cy" => &["zero", "one", "two", "few", "many", "other"],
        _ => &["other"],
    }
}

#[cfg(test)]
pub(crate) const INTEGER_SAMPLES: &[(&str, u64, &str)] = &[
    ("bm", 0, "other"),
    ("bm", 15, "other"),
    ("bm", 100, "other"),
    ("bm", 1000, "other"),
    ("bm", 10000, "other"),
    ("bm", 100000, "other"),
    ("bm", 1000000, "other"),
    ("am", 0, "one"),
    ("am", 1, "one"),
    ("am", 2, "other"),
    ("am", 17, "other"),
    ("am", 100, "other"),
    ("am", 1000, "other"),
    ("am", 10000, "other"),
    ("am", 100000, "other"),
    ("am", 1000000, "other"),
    ("ff", 0, "one"),
    ("ff", 1, "one"),
    ("ff", 2, "other"),
    ("ff", 17, "other"),
    ("ff", 100, "other"),
    ("ff", 1000, "other"),
    ("ff", 10000, "other"),
    ("ff", 100000, "other"),
    ("ff", 1000000, "other"),
    ("ast", 1, "one"),
    ("ast", 0, "other"),
    ("ast", 2, "other"),
    ("ast", 16, "other"),
    ("ast", 100, "other"),
    ("ast", 1000, "other"),
    ("ast", 10000, "other"),
    ("ast", 100000, "other"),
    ("ast", 1000000, "other"),
    ("si", 0, "one"),
    ("si", 1, "one"),
    ("si", 2, "other"),
    ("si", 17, "other"),
    ("si", 100, "other"),
    ("si", 1000, "other"),
    ("si", 10000, "other"),
    ("si", 100000, "other"),
    ("si", 1000000, "other"),
    ("ak", 0, "one"),
    ("ak", 1, "one"),
    ("ak", 2, "other"),
    ("ak", 17, "other"),
    ("ak", 100, "other"),
    ("ak", 1000, "other"),
    ("ak", 10000, "other"),
    ("ak", 100000, "other"),
    ("ak", 1000000, "other"),
    ("tzm", 0, "one"),
    ("tzm", 1, "one"),
    ("tzm", 11, "one"),
    ("tzm", 24, "one"),
    ("tzm", 2, "other"),
    ("tzm", 10, "other"),
    ("tzm", 100, "other"),
    ("tzm", 106, "other"),
    ("tzm", 1000, "other"),
    ("tzm", 10000, "other"),
    ("tzm", 100000, "other"),
    ("tzm", 1000000, "other"),
    ("af", 1, "one"),
    ("af", 0, "other"),
    ("af", 2, "other"),
    ("af", 16, "other"),
    ("af", 100, "other"),
    ("af", 1000, "other"),
    ("af", 10000, "other"),
    ("af", 100000, "other"),
    ("af", 1000000, "other"),
    ("da", 1, "one"),
    ("da", 0, "other"),
    ("da", 2, "other"),
    ("da", 16, "other"),
    ("da", 100, "other"),
    ("da", 1000, "other"),
    ("da", 10000, "other"),
    ("da", 100000, "other"),
    ("da", 1000000, "other"),
    ("is", 1, "one"),
    ("is", 21, "one"),
    ("is", 31, "one"),
    ("is", 41, "one"),
    ("is", 51, "one"),
    ("is", 61, "one"),
    ("is", 71, "one"),
    ("is", 81, "one"),
    ("is", 101, "one"),
    ("is", 1001, "one"),
    ("is", 0, "other"),
    ("is", 2, "other"),
    ("is", 16, "other"),
    ("is", 100, "other"),
    ("is", 1000, "other"),
    ("is", 10000, "other"),
    ("is", 100000, "other"),
    ("is", 1000000, "other"),
    ("mk", 1, "one"),
    ("mk", 21, "one"),
    ("mk", 31, "one"),
    ("mk", 41, "one"),
    ("mk", 51, "one"),
    ("mk", 61, "one"),
    ("mk", 71, "one"),
    ("mk", 81, "one"),
    ("mk", 101, "one"),
    ("mk", 1001, "one"),
    ("mk", 0, "other"),
    ("mk", 2, "other"),
    ("mk", 16, "other"),
    ("mk", 100, "other"),
    ("mk", 1000, "other"),
    ("mk", 10000, "other"),
    ("mk", 100000, "other"),
    ("mk", 1000000, "other"),
    ("ceb", 0, "one"),
    ("ceb", 3, "one"),
    ("ceb", 5, "one"),
    ("ceb", 7, "one"),
    ("ceb", 8, "one"),
    ("ceb", 10, "one"),
    ("ceb", 13, "one"),
    ("ceb", 15, "one"),
    ("ceb", 17, "one"),
    ("ceb", 18, "one"),
    ("ceb", 20, "one"),
    ("ceb", 21, "one"),
    ("ceb", 100, "one"),
    ("ceb", 1000, "one"),
    ("ceb", 10000, "one"),
    ("ceb", 100000, "one"),
    ("ceb", 1000000, "one"),
    ("ceb", 4, "other"),
    ("ceb", 6, "other"),
    ("ceb", 9, "other"),
    ("ceb", 14, "other"),
    ("ceb", 16, "other"),
    ("ceb", 19, "other"),
    ("ceb", 24, "other"),
    ("ceb", 26, "other"),
    ("ceb", 104, "other"),
    ("ceb", 1004, "other"),
    ("lv", 0, "zero"),
    ("lv", 10, "zero"),
    ("lv", 20, "zero"),
    ("lv", 30, "zero"),
    ("lv", 40, "zero"),
    ("lv", 50, "zero"),
    ("lv", 60, "zero"),
    ("lv", 100, "zero"),
    ("lv", 1000, "zero"),
    ("lv", 10000, "zero"),
    ("lv", 100000, "zero"),
    ("lv", 1000000, "zero"),
    ("lv", 1, "one"),
    ("lv", 21, "one"),
    ("lv", 31, "one"),
    ("lv", 41, "one"),
    ("lv", 51, "one"),
    ("lv", 61, "one"),
    ("lv", 71, "one"),
    ("lv", 81, "one"),
    ("lv", 101, "one"),
    ("lv", 1001, "one"),
    ("lv", 2, "other"),
    ("lv", 9, "other"),
    ("lv", 22, "other"),
    ("lv", 29, "other"),
    ("lv", 102, "other"),
    ("lv", 1002, "other"),
    ("lag", 0, "zero"),
    ("lag", 1, "one"),
    ("lag", 2, "other"),
    ("lag", 17, "other"),
    ("lag", 100, "other"),
    ("lag", 1000, "other"),
    ("lag", 10000, "other"),
    ("lag", 100000, "other"),
    ("lag", 1000000, "other"),
    ("blo", 0, "zero"),
    ("blo", 1, "one"),
    ("blo", 2, "other"),
    ("blo", 17, "other"),
    ("blo", 100, "other"),
    ("blo", 1000, "other"),
    ("blo", 10000, "other"),
    ("blo", 100000, "other"),
    ("blo", 1000000, "other"),
    ("he", 1, "one"),
    ("he", 2, "two"),
    ("he", 0, "other"),
    ("he", 3, "other"),
    ("he", 17, "other"),
    ("he", 100, "other"),
    ("he", 1000, "other"),
    ("he", 10000, "other"),
    ("he", 100000, "other"),
    ("he", 1000000, "other"),
    ("iu", 1, "one"),
    ("iu", 2, "two"),
    ("iu", 0, "other"),
    ("iu", 3, "other"),
    ("iu", 17, "other"),
    ("iu", 100, "other"),
    ("iu", 1000, "other"),
    ("iu", 10000, "other"),
    ("iu", 100000, "other"),
    ("iu", 1000000, "other"),
    ("shi", 0, "one"),
    ("shi", 1, "one"),
    ("shi", 2, "few"),
    ("shi", 10, "few"),
    ("shi", 11, "other"),
    ("shi", 26, "other"),
    ("shi", 100, "other"),
    ("shi", 1000, "other"),
    ("shi", 10000, "other"),
    ("shi", 100000, "other"),
    ("shi", 1000000, "other"),
    ("mo", 1, "one"),
    ("mo", 0, "few"),
    ("mo", 2, "few"),
    ("mo", 16, "few"),
    ("mo", 101, "few"),
    ("mo", 1001, "few"),
    ("mo", 20, "other"),
    ("mo", 35, "other"),
    ("mo", 100, "other"),
    ("mo", 1000, "other"),
    ("mo", 10000, "other"),
    ("mo", 100000, "other"),
    ("mo", 1000000, "other"),
    ("bs", 1, "one"),
    ("bs", 21, "one"),
    ("bs", 31, "one"),
    ("bs", 41, "one"),
    ("bs", 51, "one"),
    ("bs", 61, "one"),
    ("bs", 71, "one"),
    ("bs", 81, "one"),
    ("bs", 101, "one"),
    ("bs", 1001, "one"),
    ("bs", 2, "few"),
    ("bs", 4, "few"),
    ("bs", 22, "few"),
    ("bs", 24, "few"),
    ("bs", 32, "few"),
    ("bs", 34, "few"),
    ("bs", 42, "few"),
    ("bs", 44, "few"),
    ("bs", 52, "few"),
    ("bs", 54, "few"),
    ("bs", 62, "few"),
    ("bs", 102, "few"),
    ("bs", 1002, "few"),
    ("bs", 0, "other"),
    ("bs", 5, "other"),
    ("bs", 19, "other"),
    ("bs", 100, "other"),
    ("bs", 1000, "other"),
    ("bs", 10000, "other"),
    ("bs", 100000, "other"),
    ("bs", 1000000, "other"),
    ("fr", 0, "one"),
    ("fr", 1, "one"),
    ("fr", 1000000, "many"),
    ("fr", 2, "other"),
    ("fr", 17, "other"),
    ("fr", 100, "other"),
    ("fr", 1000, "other"),
    ("fr", 10000, "other"),
    ("fr", 100000, "other"),
    ("pt", 0, "one"),
    ("pt", 1, "one"),
    ("pt", 1000000, "many"),
    ("pt", 2, "other"),
    ("pt", 17, "other"),
    ("pt", 100, "other"),
    ("pt", 1000, "other"),
    ("pt", 10000, "other"),
    ("pt", 100000, "other"),
    ("ca", 1, "one"),
    ("ca", 1000000, "many"),
    ("ca", 0, "other"),
    ("ca", 2, "other"),
    ("ca", 16, "other"),
    ("ca", 100, "other"),
    ("ca", 1000, "other"),
    ("ca", 10000, "other"),
    ("ca", 100000, "other"),
    ("es", 1, "one"),
    ("es", 1000000, "many"),
    ("es", 0, "other"),
    ("es", 2, "other"),
    ("es", 16, "other"),
    ("es", 100, "other"),
    ("es", 1000, "other"),
    ("es", 10000, "other"),
    ("es", 100000, "other"),
    ("gd", 1, "one"),
    ("gd", 11, "one"),
    ("gd", 2, "two"),
    ("gd", 12, "two"),
    ("gd", 3, "few"),
    ("gd", 10, "few"),
    ("gd", 13, "few"),
    ("gd", 19, "few"),
    ("gd", 0, "other"),
    ("gd", 20, "other"),
    ("gd", 34, "other"),
    ("gd", 100, "other"),
    ("gd", 1000, "other"),
    ("gd", 10000, "other"),
    ("gd", 100000, "other"),
    ("gd", 1000000, "other"),
    ("sl", 1, "one"),
    ("sl", 101, "one"),
    ("sl", 201, "one"),
    ("sl", 301, "one"),
    ("sl", 401, "one"),
    ("sl", 501, "one"),
    ("sl", 601, "one"),
    ("sl", 701, "one"),
    ("sl", 1001, "one"),
    ("sl", 2, "two"),
    ("sl", 102, "two"),
    ("sl", 202, "two"),
    ("sl", 302, "two"),
    ("sl", 402, "two"),
    ("sl", 502, "two"),
    ("sl", 602, "two"),
    ("sl", 702, "two"),
    ("sl", 1002, "two"),
    ("sl", 3, "few"),
    ("sl", 4, "few"),
    ("sl", 103, "few"),
    ("sl", 104, "few"),
    ("sl", 203, "few"),
    ("sl", 204, "few"),
    ("sl", 303, "few"),
    ("sl", 304, "few"),
    ("sl", 403, "few"),
    ("sl", 404, "few"),
    ("sl", 503, "few"),
    ("sl", 504, "few"),
    ("sl", 603, "few"),
    ("sl", 604, "few"),
    ("sl", 703, "few"),
    ("sl", 704, "few"),
    ("sl", 1003, "few"),
    ("sl", 0, "other"),
    ("sl", 5, "other"),
    ("sl", 19, "other"),
    ("sl", 100, "other"),
    ("sl", 1000, "other"),
    ("sl", 10000, "other"),
    ("sl", 100000, "other"),
    ("sl", 1000000, "other"),
    ("dsb", 1, "one"),
    ("dsb", 101, "one"),
    ("dsb", 201, "one"),
    ("dsb", 301, "one"),
    ("dsb", 401, "one"),
    ("dsb", 501, "one"),
    ("dsb", 601, "one"),
    ("dsb", 701, "one"),
    ("dsb", 1001, "one"),
    ("dsb", 2, "two"),
    ("dsb", 102, "two"),
    ("dsb", 202, "two"),
    ("dsb", 302, "two"),
    ("dsb", 402, "two"),
    ("dsb", 502, "two"),
    ("dsb", 602, "two"),
    ("dsb", 702, "two"),
    ("dsb", 1002, "two"),
    ("dsb", 3, "few"),
    ("dsb", 4, "few"),
    ("dsb", 103, "few"),
    ("dsb", 104, "few"),
    ("dsb", 203, "few"),
    ("dsb", 204, "few"),
    ("dsb", 303, "few"),
    ("dsb", 304, "few"),
    ("dsb", 403, "few"),
    ("dsb", 404, "few"),
    ("dsb", 503, "few"),
    ("dsb", 504, "few"),
    ("dsb", 603, "few"),
    ("dsb", 604, "few"),
    ("dsb", 703, "few"),
    ("dsb", 704, "few"),
    ("dsb", 1003, "few"),
    ("dsb", 0, "other"),
    ("dsb", 5, "other"),
    ("dsb", 19, "other"),
    ("dsb", 100, "other"),
    ("dsb", 1000, "other"),
    ("dsb", 10000, "other"),
    ("dsb", 100000, "other"),
    ("dsb", 1000000, "other"),
    ("cs", 1, "one"),
    ("cs", 2, "few"),
    ("cs", 4, "few"),
    ("cs", 0, "other"),
    ("cs", 5, "other"),
    ("cs", 19, "other"),
    ("cs", 100, "other"),
    ("cs", 1000, "other"),
    ("cs", 10000, "other"),
    ("cs", 100000, "other"),
    ("cs", 1000000, "other"),
    ("pl", 1, "one"),
    ("pl", 2, "few"),
    ("pl", 4, "few"),
    ("pl", 22, "few"),
    ("pl", 24, "few"),
    ("pl", 32, "few"),
    ("pl", 34, "few"),
    ("pl", 42, "few"),
    ("pl", 44, "few"),
    ("pl", 52, "few"),
    ("pl", 54, "few"),
    ("pl", 62, "few"),
    ("pl", 102, "few"),
    ("pl", 1002, "few"),
    ("pl", 0, "many"),
    ("pl", 5, "many"),
    ("pl", 19, "many"),
    ("pl", 100, "many"),
    ("pl", 1000, "many"),
    ("pl", 10000, "many"),
    ("pl", 100000, "many"),
    ("pl", 1000000, "many"),
    ("be", 1, "one"),
    ("be", 21, "one"),
    ("be", 31, "one"),
    ("be", 41, "one"),
    ("be", 51, "one"),
    ("be", 61, "one"),
    ("be", 71, "one"),
    ("be", 81, "one"),
    ("be", 101, "one"),
    ("be", 1001, "one"),
    ("be", 2, "few"),
    ("be", 4, "few"),
    ("be", 22, "few"),
    ("be", 24, "few"),
    ("be", 32, "few"),
    ("be", 34, "few"),
    ("be", 42, "few"),
    ("be", 44, "few"),
    ("be", 52, "few"),
    ("be", 54, "few"),
    ("be", 62, "few"),
    ("be", 102, "few"),
    ("be", 1002, "few"),
    ("be", 0, "many"),
    ("be", 5, "many"),
    ("be", 19, "many"),
    ("be", 100, "many"),
    ("be", 1000, "many"),
    ("be", 10000, "many"),
    ("be", 100000, "many"),
    ("be", 1000000, "many"),
    ("lt", 1, "one"),
    ("lt", 21, "one"),
    ("lt", 31, "one"),
    ("lt", 41, "one"),
    ("lt", 51, "one"),
    ("lt", 61, "one"),
    ("lt", 71, "one"),
    ("lt", 81, "one"),
    ("lt", 101, "one"),
    ("lt", 1001, "one"),
    ("lt", 2, "few"),
    ("lt", 9, "few"),
    ("lt", 22, "few"),
    ("lt", 29, "few"),
    ("lt", 102, "few"),
    ("lt", 1002, "few"),
    ("lt", 0, "other"),
    ("lt", 10, "other"),
    ("lt", 20, "other"),
    ("lt", 30, "other"),
    ("lt", 40, "other"),
    ("lt", 50, "other"),
    ("lt", 60, "other"),
    ("lt", 100, "other"),
    ("lt", 1000, "other"),
    ("lt", 10000, "other"),
    ("lt", 100000, "other"),
    ("lt", 1000000, "other"),
    ("ru", 1, "one"),
    ("ru", 21, "one"),
    ("ru", 31, "one"),
    ("ru", 41, "one"),
    ("ru", 51, "one"),
    ("ru", 61, "one"),
    ("ru", 71, "one"),
    ("ru", 81, "one"),
    ("ru", 101, "one"),
    ("ru", 1001, "one"),
    ("ru", 2, "few"),
    ("ru", 4, "few"),
    ("ru", 22, "few"),
    ("ru", 24, "few"),
    ("ru", 32, "few"),
    ("ru", 34, "few"),
    ("ru", 42, "few"),
    ("ru", 44, "few"),
    ("ru", 52, "few"),
    ("ru", 54, "few"),
    ("ru", 62, "few"),
    ("ru", 102, "few"),
    ("ru", 1002, "few"),
    ("ru", 0, "many"),
    ("ru", 5, "many"),
    ("ru", 19, "many"),
    ("ru", 100, "many"),
    ("ru", 1000, "many"),
    ("ru", 10000, "many"),
    ("ru", 100000, "many"),
    ("ru", 1000000, "many"),
    ("sgs", 1, "one"),
    ("sgs", 21, "one"),
    ("sgs", 31, "one"),
    ("sgs", 41, "one"),
    ("sgs", 51, "one"),
    ("sgs", 61, "one"),
    ("sgs", 71, "one"),
    ("sgs", 81, "one"),
    ("sgs", 101, "one"),
    ("sgs", 1001, "one"),
    ("sgs", 2, "two"),
    ("sgs", 3, "few"),
    ("sgs", 9, "few"),
    ("sgs", 22, "few"),
    ("sgs", 29, "few"),
    ("sgs", 32, "few"),
    ("sgs", 102, "few"),
    ("sgs", 1002, "few"),
    ("sgs", 0, "other"),
    ("sgs", 10, "other"),
    ("sgs", 20, "other"),
    ("sgs", 30, "other"),
    ("sgs", 40, "other"),
    ("sgs", 50, "other"),
    ("sgs", 60, "other"),
    ("sgs", 100, "other"),
    ("sgs", 1000, "other"),
    ("sgs", 10000, "other"),
    ("sgs", 100000, "other"),
    ("sgs", 1000000, "other"),
    ("br", 1, "one"),
    ("br", 21, "one"),
    ("br", 31, "one"),
    ("br", 41, "one"),
    ("br", 51, "one"),
    ("br", 61, "one"),
    ("br", 81, "one"),
    ("br", 101, "one"),
    ("br", 1001, "one"),
    ("br", 2, "two"),
    ("br", 22, "two"),
    ("br", 32, "two"),
    ("br", 42, "two"),
    ("br", 52, "two"),
    ("br", 62, "two"),
    ("br", 82, "two"),
    ("br", 102, "two"),
    ("br", 1002, "two"),
    ("br", 3, "few"),
    ("br", 4, "few"),
    ("br", 9, "few"),
    ("br", 23, "few"),
    ("br", 24, "few"),
    ("br", 29, "few"),
    ("br", 33, "few"),
    ("br", 34, "few"),
    ("br", 39, "few"),
    ("br", 43, "few"),
    ("br", 44, "few"),
    ("br", 49, "few"),
    ("br", 103, "few"),
    ("br", 1003, "few"),
    ("br", 1000000, "many"),
    ("br", 0, "other"),
    ("br", 5, "other"),
    ("br", 8, "other"),
    ("br", 10, "other"),
    ("br", 20, "other"),
    ("br", 100, "other"),
    ("br", 1000, "other"),
    ("br", 10000, "other"),
    ("br", 100000, "other"),
    ("mt", 1, "one"),
    ("mt", 2, "two"),
    ("mt", 0, "few"),
    ("mt", 3, "few"),
    ("mt", 10, "few"),
    ("mt", 103, "few"),
    ("mt", 109, "few"),
    ("mt", 1003, "few"),
    ("mt", 11, "many"),
    ("mt", 19, "many"),
    ("mt", 111, "many"),
    ("mt", 117, "many"),
    ("mt", 1011, "many"),
    ("mt", 20, "other"),
    ("mt", 35, "other"),
    ("mt", 100, "other"),
    ("mt", 1000, "other"),
    ("mt", 10000, "other"),
    ("mt", 100000, "other"),
    ("mt", 1000000, "other"),
    ("ga", 1, "one"),
    ("ga", 2, "two"),
    ("ga", 3, "few"),
    ("ga", 6, "few"),
    ("ga", 7, "many"),
    ("ga", 10, "many"),
    ("ga", 0, "other"),
    ("ga", 11, "other"),
    ("ga", 25, "other"),
    ("ga", 100, "other"),
    ("ga", 1000, "other"),
    ("ga", 10000, "other"),
    ("ga", 100000, "other"),
    ("ga", 1000000, "other"),
    ("gv", 1, "one"),
    ("gv", 11, "one"),
    ("gv", 21, "one"),
    ("gv", 31, "one"),
    ("gv", 41, "one"),
    ("gv", 51, "one"),
    ("gv", 61, "one"),
    ("gv", 71, "one"),
    ("gv", 101, "one"),
    ("gv", 1001, "one"),
    ("gv", 2, "two"),
    ("gv", 12, "two"),
    ("gv", 22, "two"),
    ("gv", 32, "two"),
    ("gv", 42, "two"),
    ("gv", 52, "two"),
    ("gv", 62, "two"),
    ("gv", 72, "two"),
    ("gv", 102, "two"),
    ("gv", 1002, "two"),
    ("gv", 0, "few"),
    ("gv", 20, "few"),
    ("gv", 40, "few"),
    ("gv", 60, "few"),
    ("gv", 80, "few"),
    ("gv", 100, "few"),
    ("gv", 120, "few"),
    ("gv", 140, "few"),
    ("gv", 1000, "few"),
    ("gv", 10000, "few"),
    ("gv", 100000, "few"),
    ("gv", 1000000, "few"),
    ("gv", 3, "other"),
    ("gv", 10, "other"),
    ("gv", 13, "other"),
    ("gv", 19, "other"),
    ("gv", 23, "other"),
    ("gv", 103, "other"),
    ("gv", 1003, "other"),
    ("kw", 0, "zero"),
    ("kw", 1, "one"),
    ("kw", 2, "two"),
    ("kw", 22, "two"),
    ("kw", 42, "two"),
    ("kw", 62, "two"),
    ("kw", 82, "two"),
    ("kw", 102, "two"),
    ("kw", 122, "two"),
    ("kw", 142, "two"),
    ("kw", 1000, "two"),
    ("kw", 10000, "two"),
    ("kw", 100000, "two"),
    ("kw", 3, "few"),
    ("kw", 23, "few"),
    ("kw", 43, "few"),
    ("kw", 63, "few"),
    ("kw", 83, "few"),
    ("kw", 103, "few"),
    ("kw", 123, "few"),
    ("kw", 143, "few"),
    ("kw", 1003, "few"),
    ("kw", 21, "many"),
    ("kw", 41, "many"),
    ("kw", 61, "many"),
    ("kw", 81, "many"),
    ("kw", 101, "many"),
    ("kw", 121, "many"),
    ("kw", 141, "many"),
    ("kw", 161, "many"),
    ("kw", 1001, "many"),
    ("kw", 4, "other"),
    ("kw", 19, "other"),
    ("kw", 100, "other"),
    ("kw", 1004, "other"),
    ("kw", 1000000, "other"),
    ("ar", 0, "zero"),
    ("ar", 1, "one"),
    ("ar", 2, "two"),
    ("ar", 3, "few"),
    ("ar", 10, "few"),
    ("ar", 103, "few"),
    ("ar", 110, "few"),
    ("ar", 1003, "few"),
    ("ar", 11, "many"),
    ("ar", 26, "many"),
    ("ar", 111, "many"),
    ("ar", 1011, "many"),
    ("ar", 100, "other"),
    ("ar", 102, "other"),
    ("ar", 200, "other"),
    ("ar", 202, "other"),
    ("ar", 300, "other"),
    ("ar", 302, "other"),
    ("ar", 400, "other"),
    ("ar", 402, "other"),
    ("ar", 500, "other"),
    ("ar", 502, "other"),
    ("ar", 600, "other"),
    ("ar", 1000, "other"),
    ("ar", 10000, "other"),
    ("ar", 100000, "other"),
    ("ar", 1000000, "other"),
    ("cy", 0, "zero"),
    ("cy", 1, "one"),
    ("cy", 2, "two"),
    ("cy", 3, "few"),
    ("cy", 6, "many"),
    ("cy", 4, "other"),
    ("cy", 5, "other"),
    ("cy", 7, "other"),
    ("cy", 20, "other"),
    ("cy", 100, "other"),
    ("cy", 1000, "other"),
    ("cy", 10000, "other"),
    ("cy", 100000, "other"),
    ("cy", 1000000, "other"),
];

#[test]
fn cldr_integer_samples() {
    for &(language, n, expected) in INTEGER_SAMPLES {
        assert_eq!(category(language, n), expected, "{language}: {n}");
    }
}
