// Generated by make export-background-coreml. Source ONNX is excluded on macOS.
const ASSETS: &[Asset] = &[
    Asset { id: "detail-matting", archive: include_bytes!("../models/detail-matting.mlmodelc.tar.xz"), hash: "ce1dffadd2ad527c8cf034146eca95cb57712a26ee1bf797c2e1f41a5ecdedda", files: &[
        ("analytics/coremldata.bin", 243, "0151f182c0c9462f6fcfa3a1617d8cb071a7cc67bfc588a3c4b672fa617c11d7"),
        ("coremldata.bin", 157, "8f626d099b80cae679786dc6e2ce83aa491f223e2f4fadca159f36a699ec4116"),
        ("model.mil", 440899, "e13508927c89795206ac5a0e3555032c6422af8cb9f926f82fd38f252078dc7b"),
        ("weights/inline.bin", 85014592, "0d8a3f057cb6effd9b8b940ccdbc61bddef5fe2813bd6ba915c5526f7daebf0c"),
        ("weights/weight.bin", 26773632, "3c332f4e3d6aebfb4d96efc1ce9b70d12c770a4e50a8ca286f9ec19a4e3702c8"),
    ] },
    Asset { id: "subject-guide", archive: include_bytes!("../models/subject-guide.mlmodelc.tar.xz"), hash: "07fe85985d61498bc122c5432ee2c9743358d1fb391881ad3c1b72ced322ee2d", files: &[
        ("analytics/coremldata.bin", 243, "2dffb31e6225018c0bb1b4fc0c8a1f48179ca4d91c3b4c8b8fc79df72618dfcd"),
        ("coremldata.bin", 153, "f3dc08266900ca1f8e8e889fb8c846eb0c7c4460e4e7c95e98fad9d08133de64"),
        ("model.mil", 163597, "f05cb323b2b051c6e2895e9b475b5f701b98405521a11b6ded033f186170c0ee"),
        ("weights/weight.bin", 44056064, "80df5f936595705db25f608a14516f5acf675c423b1bda9cc990d1622bd26ada"),
    ] },
    Asset { id: "matting", archive: include_bytes!("../models/matting.mlmodelc.tar.xz"), hash: "360317283b672e41888c02a1b0f572889c429210efefee1c79617967a39cceca", files: &[
        ("analytics/coremldata.bin", 243, "e011f59dc0a364fb3c6746453a9d45b377a7cb5632375fe5db8c73b56212306e"),
        ("coremldata.bin", 156, "0daad2fe008b430978c3c96412e96b2f1bec81bd499e1a841446d1391430ca40"),
        ("model.mil", 12867, "235deb7be8ee0098b24d53c46c934c999af08b56d8a1cd685aacda9c0dc9ee9a"),
        ("weights/weight.bin", 88704, "887245b0fa2f6fed5cee343d40b9566e65cdbdec937403127ad5064c42de4be1"),
    ] },
    #[cfg(target_arch = "aarch64")]
    Asset { id: "detail-matting-gpu", archive: include_bytes!("../models/detail-matting-gpu.mlmodelc.tar.xz"), hash: "5192481c929c348555b3a2c6ddcc12925e9634d3a07a1d36c4fbcf2759bee7e8", files: &[
        ("analytics/coremldata.bin", 243, "8149b7f1c9d8e16e6557b3338fc078aaabe56e3e26262466e52f9440efa45e1b"),
        ("coremldata.bin", 318, "b4f5e32becd1573023d2d4d35a1a3bbc7cb41b37142a94fc86622c547cc9ef04"),
        ("model.mil", 539246, "302f5cfd11e34abcd335f26546668bc97a59f3ac6f54ff6ba608b7bcb32862e1"),
        ("weights/weight.bin", 55940768, "7a282de6a9e79bb1153f107708c40bce39c29227ff1fd8ce7c8c3676a3234636"),
    ] },
];
