[package]
name = "schist-tools-vector"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-i18n.workspace = true
schist-core.workspace = true
schist-plugin-api.workspace = true
schist-color.workspace = true
schist-vector.workspace = true
schist-model3d.workspace = true
