[package]
name = "schist-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-color.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
rayon.workspace = true
smallvec.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
