#!/usr/bin/env python3
"""Generate integer cardinal rules from the vendored Unicode CLDR 48 data.

Schist's count API takes u64, so fractional operands and compact exponents
are zero. Keep the CLDR expressions and their integer samples together;
the generated Rust tests exercise the samples independently of the parser.
"""

import re
import json
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "crates/i18n/data/plurals.xml"
OUTPUT = ROOT / "crates/i18n/src/plurals.rs"


def relation(text):
    match = re.fullmatch(r"([nivwftec])(?: % (\d+))? (!=|=) ([\d.,]+)", text)
    if not match:
        raise ValueError(f"Unsupported CLDR relation: {text!r}")
    operand, modulus, operator, values = match.groups()
    variable = operand in ("n", "i")
    left = "n" if variable else "0"
    if modulus:
        left += f" % {modulus}"
    alternatives = []
    for value in values.split(","):
        bounds = [int(v) for v in value.split("..")]
        if not variable:
            alternatives.append(bounds[0] <= 0 <= bounds[-1])
        elif len(bounds) == 1:
            alternatives.append(f"{left} == {bounds[0]}")
        else:
            alternatives.append(f"({bounds[0]}..={bounds[1]}).contains(&({left}))")
    if not variable:
        result = any(alternatives)
        return str(result if operator == "=" else not result).lower()
    result = " || ".join(alternatives)
    if operator == "!=":
        return f"!({result})"
    return f"({result})" if len(alternatives) > 1 else result


def expression(text):
    disjunction = []
    for conjunction in text.split(" or "):
        terms = [relation(part) for part in conjunction.split(" and ")]
        if "false" in terms:
            continue
        terms = [term for term in terms if term != "true"]
        disjunction.append(" && ".join(terms) or "true")
    result = " || ".join(disjunction) or "false"
    if result.startswith("("):
        depth = 0
        for index, char in enumerate(result):
            depth += (char == "(") - (char == ")")
            if depth == 0:
                if index == len(result) - 1:
                    result = result[1:-1]
                break
    return result


def samples(text):
    if "@integer" not in text:
        return []
    section = text.split("@integer", 1)[1].split("@decimal", 1)[0]
    result = []
    for item in section.split(","):
        item = item.strip()
        if not item or item == "…":
            continue
        for bound in item.split("~"):
            if "c" in bound:
                # Compact exponent rules differ from plain integer rules.
                # These are not inputs our u64 API represents.
                continue
            result.append(int(bound))
    return sorted(set(result))


def main():
    groups = ET.parse(DATA).findall(".//pluralRules")
    lines = [
        "// Generated by tools/generate-i18n-plurals.py; do not edit.",
        "// Unicode CLDR 48. See ../data/LICENSE-Unicode.txt.",
        "// Cardinal counts are u64: n = i, and v/w/f/t/c/e = 0.",
        "",
        "pub(crate) fn category(language: &str, n: u64) -> &'static str {",
        "    match language {",
    ]
    forms = []
    by_language = {}
    tests = []
    for group in groups:
        languages = group.get("locales").split()
        pattern = " | ".join(f'"{language}"' for language in languages)
        conditions = []
        categories = []
        for rule in group:
            category = rule.get("count")
            text = rule.text or ""
            condition = text.split("@", 1)[0].strip()
            condition = expression(condition) if condition else "true"
            if condition == "false":
                continue
            categories.append(category)
            if category != "other":
                conditions.append((condition, category))
            for sample in samples(text):
                tests.append((languages[0], sample, category))
        lines.append(f"        {pattern} => {{")
        for condition, category in conditions:
            lines.append(f'            if {condition} {{ return "{category}"; }}')
        lines.extend(['            "other"', "        }"])
        forms.append((pattern, categories))
        for language in languages:
            by_language[language] = categories
    lines.extend([
        '        _ => "other",',
        "    }",
        "}",
        "",
        "pub(crate) fn categories(language: &str) -> &'static [&'static str] {",
        "    match language {",
    ])
    for pattern, categories in forms:
        values = ", ".join(f'"{category}"' for category in categories)
        lines.append(f"        {pattern} => &[{values}],")
    lines.extend([
        '        _ => &["other"],',
        "    }",
        "}",
        "",
        "#[cfg(test)]",
        "pub(crate) const INTEGER_SAMPLES: &[(&str, u64, &str)] = &[",
    ])
    for language, sample, category in tests:
        lines.append(f'    ("{language}", {sample}, "{category}"),')
    lines.extend([
        "];",
        "",
        "#[test]",
        "fn cldr_integer_samples() {",
        "    for &(language, n, expected) in INTEGER_SAMPLES {",
        '        assert_eq!(category(language, n), expected, "{language}: {n}");',
        "    }",
        "}",
        "",
    ])
    OUTPUT.write_text("\n".join(lines))
    (DATA.parent / "plural-categories.json").write_text(
        json.dumps(by_language, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    subprocess.run(["rustfmt", "--edition", "2024", str(OUTPUT)], check=True)


if __name__ == "__main__":
    main()
