#!/usr/bin/env python3
"""Keep native language declarations and the browser loader in step with Rust.

Add the completed catalog to crates/i18n/locales.tsv and its loader strings
to web/locales/<tag>.json, then run this script. --check verifies generated
files without changing them.
"""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Generic macrolanguage tags use an existing edition. Generate the copies so
# later edits to the source edition cannot leave the generic catalog stale.
CATALOG_ALIASES = {"no": "nb", "sh": "hr"}


def registry():
    result = {}
    for line in (ROOT / "crates/i18n/locales.tsv").read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        tag, variant, native_name, direction, script = line.split("\t")
        if tag in result:
            raise ValueError(f"Duplicate locale {tag}")
        result[tag] = {"nativeName": native_name, "direction": direction, "script": script}
    return result


def outputs():
    locales = registry()
    for alias, source in CATALOG_ALIASES.items():
        if alias not in locales:
            continue
        if source not in locales:
            raise ValueError(f"{alias}: catalog source {source} must be registered")
        source_dir = ROOT / "crates/i18n/locales" / source
        for path in sorted(source_dir.glob("*.lang")):
            yield ROOT / "crates/i18n/locales" / alias / path.name, path.read_text()
        loader_source = ROOT / f"web/locales/{source}.json"
        yield ROOT / f"web/locales/{alias}.json", loader_source.read_text()
    strings = {}
    english = json.loads((ROOT / "web/locales/en.json").read_text())
    for tag in locales:
        source = CATALOG_ALIASES.get(tag, tag)
        path = ROOT / f"web/locales/{source}.json"
        entries = json.loads(path.read_text())
        if entries.keys() != english.keys():
            raise ValueError(f"{path}: loader keys differ from English")
        if any(not isinstance(value, str) or not value.strip() for value in entries.values()):
            raise ValueError(f"{path}: empty or non-string loader entry")
        strings[tag] = entries
    dump = lambda value: json.dumps(value, ensure_ascii=False, indent=2)
    yield ROOT / "web/i18n-data.js", (
        "// Generated by tools/sync-i18n.py from locales.tsv and web/locales/*.json.\n"
        f"export const LOCALES = {dump(locales)};\n\n"
        f"export const STRINGS = {dump(strings)};\n"
    )
    for platform in ("macos", "ios"):
        path = ROOT / f"packaging/{platform}/Info.plist"
        text = path.read_text()
        replacement = "<key>CFBundleLocalizations</key>\n    <array>\n"
        replacement += "".join(f"        <string>{tag}</string>\n" for tag in locales)
        replacement += "    </array>"
        text, count = re.subn(r"<key>CFBundleLocalizations</key>\s*<array>.*?</array>", replacement, text, flags=re.S)
        if count != 1:
            raise ValueError(f"{path}: expected one CFBundleLocalizations array")
        yield path, text
    path = ROOT / "packaging/android/res/xml/locales_config.xml"
    text = path.read_text()
    replacement = '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
    replacement += "".join(f'    <locale android:name="{tag}" />\n' for tag in locales)
    replacement += "</locale-config>"
    text, count = re.subn(r"<locale-config\b.*?</locale-config>", replacement, text, flags=re.S)
    if count != 1:
        raise ValueError(f"{path}: expected one locale-config")
    yield path, text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, text in outputs():
        if path.exists() and path.read_text() == text:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        parser.exit(1, "Run python3 tools/sync-i18n.py; stale files: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
